name: simple_gravatar
version: 1.0.2
author: Alif Rachmawadi <arch@subosito.com>
description: A library to generate Gravatar URL in Dart 2 based on gravatar specs.
homepage: https://github.com/subosito/simple_gravatar
dependencies:
  crypto: '>=1.0.0 <3.0.0'
dev_dependencies:
  test: '>=1.3.2'
environment:
  sdk: '>=2.0.0 <3.0.0'
